// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnyxPlataform.Models;

namespace OnyxPlataform.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20191109204137_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnyxPlataform.Models.Buy", b =>
                {
                    b.Property<string>("BuyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuyDate");

                    b.Property<string>("BuyDateDeliver");

                    b.Property<string>("BuyDetailsId");

                    b.Property<string>("CatalogueId");

                    b.Property<string>("StoreId");

                    b.HasKey("BuyId");

                    b.HasIndex("BuyDetailsId");

                    b.HasIndex("CatalogueId");

                    b.HasIndex("StoreId");

                    b.ToTable("BuyList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.BuyDetails", b =>
                {
                    b.Property<string>("BuyDetailsId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BuyDetailsDiscount");

                    b.Property<int>("BuyDetailsQuantity");

                    b.Property<double>("BuyDetailsTotalPrice");

                    b.Property<string>("ProductId");

                    b.HasKey("BuyDetailsId");

                    b.HasIndex("ProductId");

                    b.ToTable("BuyDetailsList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.BuyUser", b =>
                {
                    b.Property<string>("BuyUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserDataId");

                    b.HasKey("BuyUserId");

                    b.HasIndex("UserDataId");

                    b.ToTable("BuyUserList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Catalogue", b =>
                {
                    b.Property<string>("CatalogueID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CatalogueProductBrand");

                    b.Property<string>("CatalogueProductBuilder");

                    b.Property<string>("CatalogueProductDescription");

                    b.Property<string>("CatalogueProductModel");

                    b.Property<string>("CatalogueProductName");

                    b.Property<string>("CatalogueProductType");

                    b.Property<string>("StoreId");

                    b.HasKey("CatalogueID");

                    b.HasIndex("StoreId");

                    b.ToTable("CatalogueList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.ClassRoom", b =>
                {
                    b.Property<string>("ClassRoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassRoomDescriptions");

                    b.Property<string>("ClassRoomDirections");

                    b.Property<string>("ClassRoomName");

                    b.Property<string>("UserDataId");

                    b.HasKey("ClassRoomId");

                    b.HasIndex("UserDataId");

                    b.ToTable("ClassRoomList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassRoomId");

                    b.Property<int>("CourseCapacity");

                    b.Property<string>("CourseDescription");

                    b.Property<string>("CourseFinalDate");

                    b.Property<string>("CourseInitialDate");

                    b.Property<string>("CourseName");

                    b.HasKey("CourseId");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("CourseList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CatalogueId");

                    b.Property<string>("ProductColor");

                    b.Property<double>("ProductPrice");

                    b.Property<string>("ProductSerialNumber");

                    b.Property<string>("ProductWeight");

                    b.HasKey("ProductID");

                    b.HasIndex("CatalogueId");

                    b.ToTable("ProductList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StoreDescription");

                    b.Property<string>("StoreDirection");

                    b.Property<string>("StoreMotto");

                    b.Property<string>("StoreName");

                    b.Property<string>("UserDataId");

                    b.HasKey("StoreId");

                    b.HasIndex("UserDataId");

                    b.ToTable("StoreList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.UserData", b =>
                {
                    b.Property<string>("UserDataID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserDataCreditCard");

                    b.Property<string>("UserDataCreditCardPin");

                    b.Property<string>("UserDataDirection");

                    b.Property<string>("UserDataFirstName");

                    b.Property<string>("UserDataLastName");

                    b.Property<string>("UserDataPostalCode");

                    b.HasKey("UserDataID");

                    b.ToTable("UserDataList");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Buy", b =>
                {
                    b.HasOne("OnyxPlataform.Models.BuyDetails", "buydetails")
                        .WithMany()
                        .HasForeignKey("BuyDetailsId");

                    b.HasOne("OnyxPlataform.Models.Catalogue", "catalogue")
                        .WithMany()
                        .HasForeignKey("CatalogueId");

                    b.HasOne("OnyxPlataform.Models.Store", "store")
                        .WithMany()
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.BuyDetails", b =>
                {
                    b.HasOne("OnyxPlataform.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.BuyUser", b =>
                {
                    b.HasOne("OnyxPlataform.Models.UserData", "user")
                        .WithMany()
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Catalogue", b =>
                {
                    b.HasOne("OnyxPlataform.Models.Store", "store")
                        .WithMany()
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.ClassRoom", b =>
                {
                    b.HasOne("OnyxPlataform.Models.UserData", "user")
                        .WithMany()
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Course", b =>
                {
                    b.HasOne("OnyxPlataform.Models.ClassRoom", "clasroom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Product", b =>
                {
                    b.HasOne("OnyxPlataform.Models.Catalogue", "catalogue")
                        .WithMany()
                        .HasForeignKey("CatalogueId");
                });

            modelBuilder.Entity("OnyxPlataform.Models.Store", b =>
                {
                    b.HasOne("OnyxPlataform.Models.UserData", "user")
                        .WithMany()
                        .HasForeignKey("UserDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
